#!/bin/bash
# Used to generate the training, validation and test sets. It reads the file 
# data/audio_features.lst generated by AKFeatureExtraction.sh, which contains
# the list of feature files and splits it randomly into different partitions.
set -e

N_TST=30
N_DEV=30
N_TRA=`cat data/audio_features.lst | wc -l`
N_TRA=$[N_TRA - N_TST - N_DEV]

TMP=/tmp/audio_features_$$.tmp
sort -R data/audio_features.lst > $TMP
head -n $N_TST $TMP > data/test_audio_features.lst
head -n $[N_TST+N_DEV] $TMP | tail -n $N_DEV > data/devel_audio_features.lst
tail -n $N_TRA $TMP > data/train_audio_features.lst

exit 0